```json id="z3x6ps"
{
  "name": "JSONTest",
  "on": {
    "workflow_dispatch": {}
  },
  "jobs": {
    "test": {
      "runs-on": "windows-latest",
      "steps": [
        {
          "run": "echo JSON OK"
        }
      ]
    }
  }
}
```
